services:
  db:
    image: mysql:8.0
    container_name: ptystudybuddy-db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: psb
      MYSQL_USER: ptystudybuddy
      MYSQL_PASSWORD: randomPassword
    volumes:
      - ./database-PSB-code:/docker-entrypoint-initdb.d
      - database-PSB-data:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

volumes:
  database-PSB-data: